agents/urls.py
from CRM.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),

]

agents/models.py
# Create your models here.

agents/forms.py
from django import forms

from Leads.models import Agent


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = Agent
        fields = (
            'user',
        )

agents/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import reverse
from django.views import generic

from Leads.models import Agent
from .forms import AgentModelForm


class AgentListView(LoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


class AgentCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent-list")

    def form_valid(self, form):
        agent = form.save(commit=False)
        agent.organisation = self.request.user.userprofile
        agent.save
        return super(AgentCreateView, self).form_valid(form)


class AgentDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "agents/agent_detail.html"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


class AgentUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    form_class = AgentModelForm

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

    def get_success_url(self):
        return reverse("agents:agent-detail", kwargs={'pk': self.object.pk})


class AgentDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_delete.html"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

    def get_success_url(self):
        return reverse("agents:agent-list")

agents/templates/agents/agent_create.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'agents:agent-list' %}">Agents</a>
<hr>
<h1>Create a new agent</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button>SUBMIT</button>
</form>
{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'agents:agent-list' %}">Leads</a>
<hr>
<h1>Are you sure you want to delete agent?</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button>SUBMIT</button>
</form>
<a href="{% url 'agents:agent-detail' agent.pk %}">Cancel</a>
{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-full mx-auto flex flex-wrap">
            <div class="lg:w-full w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.username}}</h1>
                <div class="flex mb-4">
                    <a class="flex-grow text-green-500 border-b-2 border-green-500 py-2 text-lg px-1">Details</a>
                    <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 hover:text-blue-500"
                       href="{% url 'agents:agent-update' agent.pk %}">Update</a>
                    <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 hover:text-blue-500"
                       href="{% url 'agents:agent-delete' agent.pk %}">Delete</a>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Username:</span>
                    <span class="ml-auto text-gray-900">{{agent.user.username}}</span>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block content %}


<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Agents</h1>
            </div>
            <div>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'agents:agent-create' %}">Create a new
                    agent</a>
            </div>
        </div>
        <div class="flex flex-wrap -m-4">
            {% for agent in object_list %}
            <div class="p-4 lg:w-1/2 md:w-full">
                <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                    <div class="flex-grow">
                        <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                            {{agent.user.username}}
                        </h2>
                        <a , class="mt-3 text-green-500 inline-flex items-center"
                           href="{% url 'agents:agent-detail' agent.pk %}">
                            Detail View
                            <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" stroke-linecap="round"
                                 stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

agents/templates/agents/agent_update.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-full mx-auto flex flex-wrap">
            <div class="lg:w-full w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username}}</h1>
                <div class="flex mb-4">
                    <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 hover:text-blue-500"
                       href="{% url 'agents:agent-detail' agent.pk %}">Details</a>
                    <a class="flex-grow text-green-500 border-b-2 border-green-500 py-2 text-lg px-1">Update</a>
                    <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 hover:text-blue-500"
                       href="{% url 'agents:agent-delete' agent.pk %}">Delete</a>
                </div>
                <h1>Update agent {{agent.user.username}} </h1>
                <div class="flex border-t border-gray-200 py-2">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <button>SUBMIT</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}